/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * one could get a copy at https://mozilla.org/MPL/2.0/.
 */

export const CURRENCIES = {
    EUR: "EUR",
    USD: "USD",
    CODE: new Map([
        ["ar", "ARS"],
        ["at", "EUR"],
        ["au", "AUD"],
        ["be", "EUR"],
        ["bg", "BGN"],
        ["bo", "BOB"],
        ["br", "BRL"],
        ["bz", "BZD"],
        ["ca", "CAD"],
        ["ch", "CHF"],
        ["cl", "CLP"],
        ["chs", "CNY"],
        ["cht", "CNY"],
        ["co", "COU"],
        ["cr", "CRC"],
        ["cs", "CZK"],
        ["cy", "EUR"],
        ["da", "DKK"],
        ["de", "EUR"],
        ["do", "DOP"],
        ["ec", "USD"],
        ["ee", "EUR"],
        ["el", "EUR"],
        ["en", "GBP"],
        ["es", "EUR"],
        ["et", "EUR"],
        ["fi", "EUR"],
        ["fr", "EUR"],
        ["gb", "GBP"],
        ["gr", "EUR"],
        ["gt", "GTQ"],
        ["hk", "HKD"],
        ["hn", "HNL"],
        ["hu", "HUF"],
        ["ie", "EUR"],
        ["in", "INR"],
        ["is", "ISK"],
        ["it", "EUR"],
        ["ja", "JPY"],
        ["jm", "JMD"],
        ["ko", "KRW"],
        ["li", "EUR"],
        ["lt", "EUR"],
        ["lu", "EUR"],
        ["mc", "EUR"],
        ["mo", "MOP"],
        ["mt", "EUR"],
        ["mx", "MXN"],
        ["ni", "NIO"],
        ["nl", "EUR"],
        ["no", "NOK"],
        ["nz", "NZD"],
        ["pa", "PAB"],
        ["pe", "PEN"],
        ["ph", "PHP"],
        ["pl", "PLN"],
        ["pr", "USD"],
        ["pt", "EUR"],
        ["py", "PYG"],
        ["ro", "RON"],
        ["ru", "RUB"],
        ["se", "SEK"],
        ["sg", "SGD"],
        ["sk", "EUR"],
        ["sl", "EUR"],
        ["sp", "RSD"],
        ["sv", "USD"],
        ["tr", "TRY"],
        ["tt", "TTD"],
        ["tw", "TWD"],
        ["uy", "UYU"],
        ["us", "USD"],
        ["ve", "VES"],
        ["za", "ZAR"],
        ["zw", "ZWD"]
    ])
} as const;
