/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * one could get a copy at https://mozilla.org/MPL/2.0/.
 */

import type {StoresConfigType} from "@/domain/types";

export const ERROR_CATEGORY = {
    DATABASE: "database",
    NETWORK: "network",
    VALIDATION: "validation",
    BUSINESS: "business",
    BROWSER_API: "browser",
    NOTIFICATION_API: "notification",
    STORAGE_API: "storage",
    STORE: "memory"
} as const;

/**
 * Stable identifiers for validation errors.
 * These map to i18n keys.
 */
export const VALIDATION_CODES = {
    REQUIRED: "required",
    INVALID_FORMAT: "invalid_format",
    INVALID_LENGTH: "invalid_length",
    INVALID_CHECKSUM: "invalid_checksum",
    DUPLICATE: "duplicate",
    NEGATIVE_VALUE: "negative_value",
    ONE_OF_TWO_REQUIRED: "one_of_two_required",
    INVALID_COUNTRY: "invalid_country",
    INVALID_BANK: "invalid_bank",
    INVALID_REGION: "invalid_region",
    INVALID_BRANCH: "invalid_branch",
    TEST_BIC: "test_bic",
    MAX_LENGTH: "max_length",
    MUST_BEGIN_WITH_LETTER: "must_begin_with_letter"
} as const;

export const VALID_COUNTRY_CODES: ReadonlySet<string> = new Set([
    "AD",
    "AE",
    "AF",
    "AG",
    "AI",
    "AL",
    "AM",
    "AO",
    "AQ",
    "AR",
    "AS",
    "AT",
    "AU",
    "AW",
    "AX",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BL",
    "BM",
    "BN",
    "BO",
    "BQ",
    "BR",
    "BS",
    "BT",
    "BV",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CC",
    "CD",
    "CF",
    "CG",
    "CH",
    "CI",
    "CK",
    "CL",
    "CM",
    "CN",
    "CO",
    "CR",
    "CU",
    "CV",
    "CW",
    "CX",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "EH",
    "ER",
    "ES",
    "ET",
    "FI",
    "FJ",
    "FK",
    "FM",
    "FO",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GF",
    "GG",
    "GH",
    "GI",
    "GL",
    "GM",
    "GN",
    "GP",
    "GQ",
    "GR",
    "GS",
    "GT",
    "GU",
    "GW",
    "GY",
    "HK",
    "HM",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IM",
    "IN",
    "IO",
    "IQ",
    "IR",
    "IS",
    "IT",
    "JE",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KP",
    "KR",
    "KW",
    "KY",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MF",
    "MG",
    "MH",
    "MK",
    "ML",
    "MM",
    "MN",
    "MO",
    "MP",
    "MQ",
    "MR",
    "MS",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NC",
    "NE",
    "NF",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NU",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PF",
    "PG",
    "PH",
    "PK",
    "PL",
    "PM",
    "PN",
    "PR",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RE",
    "RO",
    "RS",
    "RU",
    "RW",
    "SA",
    "SB",
    "SC",
    "SD",
    "SE",
    "SG",
    "SH",
    "SI",
    "SJ",
    "SK",
    "SL",
    "SM",
    "SN",
    "SO",
    "SR",
    "SS",
    "ST",
    "SV",
    "SX",
    "SY",
    "SZ",
    "TC",
    "TD",
    "TF",
    "TG",
    "TH",
    "TJ",
    "TK",
    "TL",
    "TM",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "UM",
    "US",
    "UY",
    "UZ",
    "VA",
    "VC",
    "VE",
    "VG",
    "VI",
    "VN",
    "VU",
    "WF",
    "WS",
    "XS",
    "XK",
    "YE",
    "YT",
    "ZA",
    "ZM",
    "ZW"
]);

export const DATE = {
    ISO: "1970-01-01",
    ISO_DATE_REGEX: /^\d{4}-\d{2}-\d{2}$/,
    ZERO_TIME: 0
} as const;

export const COMPONENTS = {
    TITLE_BAR: {
        LOGO: "../assets/icon64.png"
    },
    DYNAMIC_LIST: {
        TYPES: {
            MARKETS: "markets",
            EXCHANGES: "exchanges"
        }
    },
    CHECKBOX_GRID: {
        TYPES: {
            INDEXES: "indexes",
            MATERIALS: "materials"
        }
    },
    DIALOGS: {
        FADE_IN_STOCK: "fadeInStock",
        ADD_ACCOUNT: "addAccount",
        UPDATE_ACCOUNT: "updateAccount",
        DELETE_ACCOUNT: "deleteAccount",
        ADD_STOCK: "addStock",
        UPDATE_STOCK: "updateStock",
        DELETE_STOCK: "deleteStock",
        ADD_BOOKING_TYPE: "addBookingType",
        DELETE_BOOKING_TYPE: "deleteBookingType",
        UPDATE_BOOKING_TYPE: "updateBookingType",
        ADD_BOOKING: "addBooking",
        UPDATE_BOOKING: "updateBooking",
        DELETE_BOOKING: "deleteBooking",
        EXPORT_DATABASE: "exportDatabase",
        IMPORT_DATABASE: "importDatabase",
        SHOW_ACCOUNTING: {
            NAME: "showAccounting",
            ALL_YEARS_ID: 1000
        },
        SHOW_DIVIDEND: "showDividend",
        UPDATE_QUOTE: "updateQuote",
        DELETE_ACCOUNT_CONFIRMATION: "deleteAccountConfirmation",
        OPEN_LINK: "openLink",
        PLACEHOLDER: {
            ACCOUNT_LOGO_URL: "z. B. https://www.ing.de"
        }
    }
} as const;

export const CURRENCIES = {
    EUR: "EUR",
    USD: "USD",
    CODE: new Map([
        ["ar", "ARS"],
        ["at", "EUR"],
        ["au", "AUD"],
        ["be", "EUR"],
        ["bg", "BGN"],
        ["bo", "BOB"],
        ["br", "BRL"],
        ["bz", "BZD"],
        ["ca", "CAD"],
        ["ch", "CHF"],
        ["cl", "CLP"],
        ["chs", "CNY"],
        ["cht", "CNY"],
        ["co", "COU"],
        ["cr", "CRC"],
        ["cs", "CZK"],
        ["cy", "EUR"],
        ["da", "DKK"],
        ["de", "EUR"],
        ["do", "DOP"],
        ["ec", "USD"],
        ["ee", "EUR"],
        ["el", "EUR"],
        ["en", "GBP"],
        ["es", "EUR"],
        ["et", "EUR"],
        ["fi", "EUR"],
        ["fr", "EUR"],
        ["gb", "GBP"],
        ["gr", "EUR"],
        ["gt", "GTQ"],
        ["hk", "HKD"],
        ["hn", "HNL"],
        ["hu", "HUF"],
        ["ie", "EUR"],
        ["in", "INR"],
        ["is", "ISK"],
        ["it", "EUR"],
        ["ja", "JPY"],
        ["jm", "JMD"],
        ["ko", "KRW"],
        ["li", "EUR"],
        ["lt", "EUR"],
        ["lu", "EUR"],
        ["mc", "EUR"],
        ["mo", "MOP"],
        ["mt", "EUR"],
        ["mx", "MXN"],
        ["ni", "NIO"],
        ["nl", "EUR"],
        ["no", "NOK"],
        ["nz", "NZD"],
        ["pa", "PAB"],
        ["pe", "PEN"],
        ["ph", "PHP"],
        ["pl", "PLN"],
        ["pr", "USD"],
        ["pt", "EUR"],
        ["py", "PYG"],
        ["ro", "RON"],
        ["ru", "RUB"],
        ["se", "SEK"],
        ["sg", "SGD"],
        ["sk", "EUR"],
        ["sl", "EUR"],
        ["sp", "RSD"],
        ["sv", "USD"],
        ["tr", "TRY"],
        ["tt", "TTD"],
        ["tw", "TWD"],
        ["uy", "UYU"],
        ["us", "USD"],
        ["ve", "VES"],
        ["za", "ZAR"],
        ["zw", "ZWD"]
    ])
} as const;

export const FETCH = {
    PROVIDERS: {
        goyax: {
            NAME: "Goyax",
            HOME: "https://www.goyax.de/",
            QUOTE: "https://www.goyax.de/aktien/"
        },
        fnet: {
            NAME: "Finanzen.Net",
            HOME: "https://www.finanzen.net/aktienkurse/",
            QUOTE: "https://www.finanzen.net/suchergebnis.asp?_search="
        },
        wstreet: {
            NAME: "Wallstreet-Online",
            HOME: "https://www.wallstreet-online.de",
            QUOTE: "https://www.wallstreet-online.de/_rpc/json/search/auto/searchInst/"
        },
        acheck: {
            NAME: "Aktien-Check",
            HOME: "https://m.aktiencheck.de/",
            QUOTE: "https://m.aktiencheck.de/quotes/suche/?search="
        },
        ard: {
            NAME: "ARD",
            HOME: "https://www.tagesschau.de/wirtschaft/boersenkurse/",
            QUOTE: "https://www.tagesschau.de/wirtschaft/boersenkurse/suche/?suchbegriff="
        },
        tgate: {
            NAME: "Tradegate",
            HOME: "https://www.tradegate.de/",
            QUOTE: "https://www.tradegate.de/orderbuch.php?isin="
        }
    }
} as const;

export const INDEXED_DB = {
    NAME: "kontenmanager.db",
    INVALID_ID: -1,
    STORE: {
        ACCOUNTS: {
            NAME: "accounts",
            FIELDS: {
                ID: "cID",
                SWIFT: "cSwift",
                LOGO_URL: "cLogoUrl",
                IBAN: "cIban",
                WITH_DEPOT: "cWithDepot"
            }
        },
        BOOKINGS: {
            NAME: "bookings",
            FIELDS: {
                ID: "cID",
                BOOK_DATE: "cBookDate",
                EX_DATE: "cExDate",
                COUNT: "cCount",
                CREDIT: "cCredit",
                DEBIT: "cDebit",
                DESCRIPTION: "cDescription",
                BOOKING_TYPE_ID: "cBookingTypeID",
                ACCOUNT_NUMBER_ID: "cAccountNumberID",
                STOCK_ID: "cStockID",
                SOLI: "cSoli",
                MARKET_PLACE: "cMarketPlace",
                TAX: "cTax",
                FEE: "cFee",
                SOURCE_TAX: "cSourceTax",
                TRANSACTION_TAX: "cTransactionTax"
            }
        },
        BOOKING_TYPES: {
            NAME: "bookingTypes",
            FIELDS: {
                ID: "cID",
                NAME: "cName",
                ACCOUNT_NUMBER_ID: "cAccountNumberID"
            },
            NONE: -1,
            BUY: 1,
            SELL: 2,
            DIVIDEND: 3,
            CREDIT: 4,
            DEBIT: 5,
            OTHER: 4,
            FEE: 5,
            TAX: 6,
            STOCKTAX: 7,
            SOURCETAX: 8
        },
        STOCKS: {
            NAME: "stocks",
            FIELDS: {
                ID: "cID",
                ISIN: "cISIN",
                SYMBOL: "cSymbol",
                NAME: "cName",
                COUNT: "cCount",
                BUY_VALUE: "cBuyValue",
                BUY_DATE: "cBuyDate",
                RATE: "cRate",
                URL: "cURL",
                MEETING_DAY: "cMeetingDay",
                QUARTER_DAY: "cQuarterDay",
                COMPANY: "cCompany",
                FADE_OUT: "cFadeOut",
                FIRST_PAGE: "cFirstPage",
                ACCOUNT_NUMBER_ID: "cAccountNumberID"
            }
        },
        STOCK_MEMORY: {
            mPortfolio: 0,
            mInvest: 0,
            mChange: 0,
            mBuyValue: 0,
            mEuroChange: 0,
            mMin: 0,
            mValue: 0,
            mMax: 0,
            mDividendYielda: 0,
            mDividendYeara: 0,
            mDividendYieldb: 0,
            mDividendYearb: 0,
            mRealDividend: 0,
            mRealBuyValue: 0,
            mDeleteable: false
        }
    },
    LEGACY_IMPORT_VERSION: 25,
    CURRENT_VERSION: 27,
    MAX_FILE_SIZE: 64 * 1024 * 1024
} as const;

/**
 * Valid IndexedDB store names.
 * Used for runtime validation and compile-time narrowing.
 */
export const VALID_STORES = [
    INDEXED_DB.STORE.ACCOUNTS.NAME,
    INDEXED_DB.STORE.BOOKINGS.NAME,
    INDEXED_DB.STORE.STOCKS.NAME,
    INDEXED_DB.STORE.BOOKING_TYPES.NAME
] as const;

export type ValidStoreNameType = (typeof VALID_STORES)[number];

export const SETTINGS: StoresConfigType = {
    INDEXES: {
        dax: "DAX",
        dow: "Dow Jones",
        nasdaq: "NASDAQ Comp.",
        nikkei: "NIKKEI 225",
        hang: "Hang Seng",
        ibex: "IBEX 35",
        straits: "Straits Times",
        asx: "Australia All Ordinaries",
        rts: "RTS",
        bovespa: "BOVESPA",
        sensex: "SENSEX",
        sci: "Shanghai Composite",
        ftse: "FTSE 100",
        smi: "SMI",
        cac: "CAC 40",
        stoxx: "Euro Stoxx 50",
        tsx: "S&P/TSX",
        sp: "S&P 500"
    },
    MATERIALS: {
        au: "Goldpreis",
        ag: "Silberpreis",
        brent: "Ölpreis (Brent)",
        wti: "Ölpreis (WTI)",
        cu: "Kupferpreis",
        pt: "Platinpreis",
        al: "Aluminiumpreis",
        ni: "Nickelpreis",
        sn: "Zinnpreis",
        pb: "Bleipreis",
        pd: "Palladiumpreis"
    }
} as const;

export const BROWSER_STORAGE = {
    ACTIVE_ACCOUNT_ID: {key: "sActiveAccountId", value: -1},
    SKIN: {key: "sSkin", value: "ocean"},
    BOOKINGS_PER_PAGE: {key: "sBookingsPerPage", value: 9},
    STOCKS_PER_PAGE: {key: "sStocksPerPage", value: 9},
    DIVIDENDS_PER_PAGE: {key: "sDividendsPerPage", value: 9},
    SUMS_PER_PAGE: {key: "sSumsPerPage", value: 11},
    SERVICE: {key: "sService", value: "wstreet"},
    EXCHANGES: {key: "sExchanges", value: ["EURUSD"]},
    INDEXES: {key: "sIndexes", value: ["dax", "dow"]},
    MARKETS: {key: "sMarkets", value: ["Frankfurt", "XETRA"]},
    MATERIALS: {key: "sMaterials", value: ["au", "brent"]}
} as const;
