/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * one could get a copy at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2025-2026, Martin Berner, kontenmanager@gmx.de. All rights reserved.
 */

import { AppError, ERROR_CATEGORY, ERROR_CODES } from "@/domains/errors";
import { DomainUtils } from "@/domains/utils";

/**
 * Low-level base class for IndexedDB operations.
 *
 * Provides typed wrappers around common CRUD and transaction patterns used by
 * the repositories and the `DatabaseService`.
 */
export class IndexedDbBase {
  protected db: IDBDatabase | null = null;
  protected connected: boolean = false;

  /**
   * Executes a callback within an IndexedDB transaction and resolves when the
   * transaction completes.
   *
   * @param storeNames - One or more store names to include in the transaction.
   * @param mode - Transaction mode, e.g. `readonly` or `readwrite`.
   * @param callback - Async function that performs the operation using the tx.
   * @returns Resolves with the callback result after tx completion.
   */
  async withTransaction<T>(
    storeNames: string | string[],
    mode: IDBTransactionMode,
    callback: (_tx: IDBTransaction) => Promise<T>
  ): Promise<T> {
    await this.ensureConnected();
    const tx = this.db!.transaction(storeNames, mode);
    try {
      const result = await callback(tx);
      return new Promise((resolve, reject) => {
        tx.oncomplete = () => resolve(result);
        tx.onerror = () => reject(tx.error);
        tx.onabort = () => reject(new Error("Transaction aborted"));
      });
    } catch (err) {
      tx.abort();
      throw err;
    }
  }

  /**
   * Adds a record to the given object store.
   * If the payload contains a `cID` property, it is removed to respect
   * `autoIncrement` behavior.
   *
   * @param storeName - Target object store name.
   * @param data - Record to insert.
   * @param tx - Optional existing transaction.
   * @returns The new primary key generated by IndexedDB.
   */
  async add<T>(
    storeName: string,
    data: T,
    tx?: IDBTransaction
  ): Promise<number> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readwrite"));
    const store = transaction.objectStore(storeName);

    // Remove cID if it exists, as IndexedDB with autoIncrement doesn't allow it
    const addData: any = { ...data };
    if ("cID" in addData) {
      delete addData.cID;
    }

    const request = store.add(addData);

    return new Promise((resolve, reject) => {
      request.onsuccess = () => resolve(request.result as number);
      request.onerror = () =>
        reject(
          new AppError(
            ERROR_CODES.SERVICES.DATABASE.BASE.B,
            ERROR_CATEGORY.DATABASE,
            false
          )
        );
    });
  }

  /**
   * Retrieves a single record by primary key.
   *
   * @param storeName - Object store name.
   * @param key - Primary key value.
   * @param tx - Optional existing transaction.
   * @returns Found record or `null` if not present.
   */
  async get<T>(
    storeName: string,
    key: IDBValidKey,
    tx?: IDBTransaction
  ): Promise<T | null> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readonly"));
    const store = transaction.objectStore(storeName);
    const request = store.get(key);

    return new Promise((resolve, reject) => {
      request.onsuccess = () => resolve((request.result as T) || null);
      request.onerror = () =>
        reject(
          new AppError(
            ERROR_CODES.SERVICES.DATABASE.BASE.C,
            ERROR_CATEGORY.DATABASE,
            false
          )
        );
    });
  }

  /**
   * Retrieves all records from a store.
   *
   * @param storeName - Object store name.
   * @param tx - Optional existing transaction.
   * @returns All records as an array.
   */
  async getAll<T>(storeName: string, tx?: IDBTransaction): Promise<T[]> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readonly"));
    const store = transaction.objectStore(storeName);
    const request = store.getAll();

    return new Promise((resolve, reject) => {
      request.onsuccess = () => resolve(request.result as T[]);
      request.onerror = () =>
        reject(
          new AppError(
            ERROR_CODES.SERVICES.DATABASE.BASE.D,
            ERROR_CATEGORY.DATABASE,
            false
          )
        );
    });
  }

  /**
   * Updates or inserts a record in a store using `put`.
   *
   * @param storeName - Object store name.
   * @param data - Record to upsert.
   * @param tx - Optional existing transaction.
   * @returns The primary key of the stored record.
   */
  async update<T>(
    storeName: string,
    data: T,
    tx?: IDBTransaction
  ): Promise<IDBValidKey> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readwrite"));
    const store = transaction.objectStore(storeName);
    const request = store.put(data);

    return new Promise((resolve, reject) => {
      request.onsuccess = () => resolve(request.result);
      request.onerror = () =>
        reject(
          new AppError(
            ERROR_CODES.SERVICES.DATABASE.BASE.E,
            ERROR_CATEGORY.DATABASE,
            false
          )
        );
    });
  }

  /**
   * Deletes a record by primary key.
   *
   * @param storeName - Object store name.
   * @param key - Primary key to delete.
   * @param tx - Optional existing transaction.
   */
  async remove(
    storeName: string,
    key: IDBValidKey,
    tx?: IDBTransaction
  ): Promise<void> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readwrite"));
    const store = transaction.objectStore(storeName);
    const request = store.delete(key);

    return new Promise((resolve, reject) => {
      request.onsuccess = () => resolve();
      request.onerror = () =>
        reject(
          new AppError(
            ERROR_CODES.SERVICES.DATABASE.BASE.F,
            ERROR_CATEGORY.DATABASE,
            false
          )
        );
    });
  }

  /**
   * Clears all records from the specified store.
   *
   * @param storeName - Object store name.
   * @param tx - Optional existing transaction.
   */
  async clear(storeName: string, tx?: IDBTransaction): Promise<void> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readwrite"));
    const store = transaction.objectStore(storeName);
    const request = store.clear();

    return new Promise((resolve, reject) => {
      request.onsuccess = () => resolve();
      request.onerror = () =>
        reject(
          new AppError(
            ERROR_CODES.SERVICES.DATABASE.BASE.G,
            ERROR_CATEGORY.DATABASE,
            false
          )
        );
    });
  }

  /**
   * Retrieves all records from an index using a key or key range.
   *
   * @param storeName - Object store name containing the index.
   * @param indexName - Index name.
   * @param query - Index key or key range.
   * @param tx - Optional existing transaction.
   * @returns Matching records as an array.
   */
  async getAllByIndex<T>(
    storeName: string,
    indexName: string,
    query: IDBValidKey | IDBKeyRange,
    tx?: IDBTransaction
  ): Promise<T[]> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readonly"));
    const store = transaction.objectStore(storeName);
    const index = store.index(indexName);
    const request = index.getAll(query);

    return new Promise((resolve, reject) => {
      request.onsuccess = () => resolve(request.result as T[]);
      request.onerror = () =>
        reject(
          new AppError(
            ERROR_CODES.SERVICES.DATABASE.BASE.H,
            ERROR_CATEGORY.DATABASE,
            false
          )
        );
    });
  }

  /**
   * Deletes all records matching the query by iterating a cursor on the index.
   *
   * @param index - The index to open a cursor on.
   * @param query - Key or key range to match.
   */
  async deleteByCursor(
    index: IDBIndex,
    query: IDBValidKey | IDBKeyRange
  ): Promise<void> {
    return new Promise((resolve, reject) => {
      const req = index.openCursor(query);
      req.onsuccess = () => {
        const cursor = req.result;
        if (cursor) {
          cursor.delete();
          cursor.continue();
        } else {
          resolve();
        }
      };
      req.onerror = () =>
        reject(
          new AppError(
            ERROR_CODES.SERVICES.DATABASE.BASE.A,
            ERROR_CATEGORY.DATABASE,
            false
          )
        );
    });
  }

  /**
   * Ensures a database connection exists. Throws if not connected.
   */
  protected async ensureConnected(): Promise<void> {
    if (!this.db) {
      throw new AppError(
        ERROR_CODES.SERVICES.DATABASE.BASE.I,
        ERROR_CATEGORY.DATABASE,
        false
      );
    }
  }

  /**
   * Creates an auto-managed transaction for a single store.
   *
   * @param storeName - Object store name.
   * @param mode - Transaction mode.
   * @returns An open transaction instance.
   */
  private async getAutoTransaction(
    storeName: string,
    mode: IDBTransactionMode
  ): Promise<IDBTransaction> {
    await this.ensureConnected();
    return this.db!.transaction(storeName, mode);
  }
}

DomainUtils.log("SERVICES DATABASE base");
