/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * one could get a copy at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) 2025-2026, Martin Berner, kontenmanager@gmx.de. All rights reserved.
 */

import { AppError, ERROR_CATEGORY, ERROR_CODES } from "@/domains/errors";
import { DomainUtils } from "@/domains/utils";

/**
 * Low-level base class for IndexedDB operations.
 *
 * Provides typed wrappers around common CRUD and transaction patterns used by
 * the repositories and the `DatabaseService`.
 */
export class IndexedDbBase {
  protected db: IDBDatabase | null = null;
  protected connected: boolean = false;

  /**
   * Executes a callback within an IndexedDB transaction and resolves when the
   * transaction completes.
   *
   * @param storeNames - One or more store names to include in the transaction.
   * @param mode - Transaction mode, e.g. `readonly` or `readwrite`.
   * @param callback - Async function that performs the operation using the tx.
   * @returns Resolves with the callback result after tx completion.
   */
  async withTransaction<T>(
    storeNames: string | string[],
    mode: IDBTransactionMode,
    callback: (_tx: IDBTransaction) => Promise<T>
  ): Promise<T> {
    await this.ensureConnected();
    const tx = this.db!.transaction(storeNames, mode);

    try {
      const result = await callback(tx);

      // Wait for the transaction to complete
      await this.waitForTransactionComplete(tx);

      return result;
    } catch (err) {
      tx.abort();
      throw err;
    }
  }

  /**
   * Waits for a transaction to complete or fail
   */
  private waitForTransactionComplete(tx: IDBTransaction): Promise<void> {
    return new Promise((resolve, reject) => {
      tx.oncomplete = () => resolve();
      tx.onerror = () => reject(tx.error);
      tx.onabort = () => reject(new Error("Transaction aborted"));
    });
  }

  /**
   * Adds a record to the given object store.
   * If the payload contains a `cID` property, it is removed to respect
   * `autoIncrement` behavior.
   *
   * @param storeName - Target object store name.
   * @param data - Record to insert.
   * @param tx - Optional existing transaction.
   * @returns The new primary key generated by IndexedDB (always a number with autoIncrement).
   */
  async add<T>(
    storeName: string,
    data: T,
    tx?: IDBTransaction
  ): Promise<number> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readwrite"));
    const store = transaction.objectStore(storeName);

    // Remove cID if it exists, as IndexedDB with autoIncrement doesn't allow it
    const addData: Omit<T, "cID"> = { ...data };
    if ("cID" in addData) {
      delete addData.cID;
    }

    const result = await this.executeRequest(
      store.add(addData),
      ERROR_CODES.SERVICES.DATABASE.BASE.B
    );
    return result as number;
  }

  /**
   * Retrieves a single record by primary key.
   *
   * @param storeName - Object store name.
   * @param key - Primary key value (number for our autoIncrement keys).
   * @param tx - Optional existing transaction.
   * @returns Found record or `null` if not present.
   */
  async get<T>(
    storeName: string,
    key: number,
    tx?: IDBTransaction
  ): Promise<T | null> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readonly"));
    const store = transaction.objectStore(storeName);

    const result = await this.executeRequest<T>(
      store.get(key),
      ERROR_CODES.SERVICES.DATABASE.BASE.C
    );

    return result || null;
  }

  /**
   * Retrieves all records from a store.
   *
   * @param storeName - Object store name.
   * @param tx - Optional existing transaction.
   * @returns All records as an array.
   */
  async getAll<T>(storeName: string, tx?: IDBTransaction): Promise<T[]> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readonly"));
    const store = transaction.objectStore(storeName);

    return this.executeRequest<T[]>(
      store.getAll(),
      ERROR_CODES.SERVICES.DATABASE.BASE.D
    );
  }

  /**
   * Updates or inserts a record in a store using `put`.
   *
   * @param storeName - Object store name.
   * @param data - Record to upsert.
   * @param tx - Optional existing transaction.
   * @returns The primary key of the stored record (always a number with autoIncrement).
   */
  async update<T>(
    storeName: string,
    data: T,
    tx?: IDBTransaction
  ): Promise<number> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readwrite"));
    const store = transaction.objectStore(storeName);

    const result = await this.executeRequest(
      store.put(data),
      ERROR_CODES.SERVICES.DATABASE.BASE.E
    );
    return result as number;
  }

  /**
   * Deletes a record by primary key.
   *
   * @param storeName - Object store name.
   * @param key - Primary key to delete (number for our autoIncrement keys).
   * @param tx - Optional existing transaction.
   */
  async remove(
    storeName: string,
    key: number,
    tx?: IDBTransaction
  ): Promise<void> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readwrite"));
    const store = transaction.objectStore(storeName);

    await this.executeRequest<undefined>(
      store.delete(key),
      ERROR_CODES.SERVICES.DATABASE.BASE.F
    );
  }

  /**
   * Clears all records from the specified store.
   *
   * @param storeName - Object store name.
   * @param tx - Optional existing transaction.
   */
  async clear(storeName: string, tx?: IDBTransaction): Promise<void> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readwrite"));
    const store = transaction.objectStore(storeName);

    await this.executeRequest<undefined>(
      store.clear(),
      ERROR_CODES.SERVICES.DATABASE.BASE.G
    );
  }

  /**
   * Retrieves all records from an index using a key or key range.
   *
   * @param storeName - Object store name containing the index.
   * @param indexName - Index name.
   * @param query - Index key or key range.
   * @param tx - Optional existing transaction.
   * @returns Matching records as an array.
   */
  async getAllByIndex<T>(
    storeName: string,
    indexName: string,
    query: IDBValidKey | IDBKeyRange,
    tx?: IDBTransaction
  ): Promise<T[]> {
    const transaction =
      tx || (await this.getAutoTransaction(storeName, "readonly"));
    const store = transaction.objectStore(storeName);
    const index = store.index(indexName);

    return this.executeRequest<T[]>(
      index.getAll(query),
      ERROR_CODES.SERVICES.DATABASE.BASE.H
    );
  }

  /**
   * Deletes all records matching the query by iterating a cursor on the index.
   *
   * @param index - The index to open a cursor on.
   * @param query - Key or key range to match.
   */
  async deleteByCursor(
    index: IDBIndex,
    query: IDBValidKey | IDBKeyRange
  ): Promise<void> {
    return new Promise((resolve, reject) => {
      const req = index.openCursor(query);
      req.onsuccess = () => {
        const cursor = req.result;
        if (cursor) {
          cursor.delete();
          cursor.continue();
        } else {
          resolve();
        }
      };
      req.onerror = () =>
        reject(
          new AppError(
            ERROR_CODES.SERVICES.DATABASE.BASE.A,
            ERROR_CATEGORY.DATABASE,
            false
          )
        );
    });
  }

  /**
   * Executes an IDBRequest and returns a Promise
   * @param request - The IDBRequest to execute
   * @param errorCode - Error code to use if the request fails
   * @returns Promise resolving to the request result
   */
  private executeRequest<T>(
    request: IDBRequest<T>,
    errorCode: string
  ): Promise<T> {
    return new Promise((resolve, reject) => {
      request.onsuccess = () => resolve(request.result);
      request.onerror = () =>
        reject(new AppError(errorCode, ERROR_CATEGORY.DATABASE, false));
    });
  }

  /**
   * Ensures a database connection exists. Throws if not connected.
   */
  protected async ensureConnected(): Promise<void> {
    if (!this.db) {
      throw new AppError(
        ERROR_CODES.SERVICES.DATABASE.BASE.I,
        ERROR_CATEGORY.DATABASE,
        false
      );
    }
  }

  /**
   * Creates an auto-managed transaction for a single store.
   *
   * @param storeName - Object store name.
   * @param mode - Transaction mode.
   * @returns An open transaction instance.
   */
  private async getAutoTransaction(
    storeName: string,
    mode: IDBTransactionMode
  ): Promise<IDBTransaction> {
    await this.ensureConnected();
    return this.db!.transaction(storeName, mode);
  }
}

/**
 * Base repository class that provides common patterns for account-scoped operations
 * All repositories dealing with account-scoped data should extend this class
 */
export class BaseRepository {
  constructor(protected _dbBase: IndexedDbBase) {}

  /**
   * Generic method to get all records for a given account
   * @param storeName - The name of the object store
   * @param indexName - The name of the account index
   * @param accountId - The account ID to filter by
   * @param tx - Optional existing transaction
   * @returns List of records for the account
   */
  protected async _getAllByAccount<T>(
    storeName: string,
    indexName: string,
    accountId: number,
    tx?: IDBTransaction
  ): Promise<T[]> {
    return this._dbBase.getAllByIndex<T>(storeName, indexName, accountId, tx);
  }

  /**
   * Generic method to delete all records for a given account
   * @param storeName - The name of the object store
   * @param indexName - The name of the account index
   * @param accountId - The account ID to filter by
   * @param tx - Required open readwrite transaction
   */
  protected async _deleteByAccount(
    storeName: string,
    indexName: string,
    accountId: number,
    tx: IDBTransaction
  ): Promise<void> {
    const store = tx.objectStore(storeName);
    const index = store.index(indexName);
    return this._dbBase.deleteByCursor(index, IDBKeyRange.only(accountId));
  }

  /**
   * Generic method to get all records from a store
   * @param storeName - The name of the object store
   * @param tx - Optional existing transaction
   * @returns All records
   */
  protected async _getAll<T>(
    storeName: string,
    tx?: IDBTransaction
  ): Promise<T[]> {
    return this._dbBase.getAll<T>(storeName, tx);
  }

  /**
   * Generic method to delete a record by ID
   * @param storeName - The name of the object store
   * @param id - The primary key to delete
   * @param tx - Optional existing transaction
   */
  protected async _delete(
    storeName: string,
    id: number,
    tx?: IDBTransaction
  ): Promise<void> {
    return this._dbBase.remove(storeName, id, tx);
  }
}

DomainUtils.log("SERVICES DATABASE base");
